dappx/urls.py
# dappx/urls.py

from django.conf.urls import url
from dappx import views

# SET THE NAMESPACE!
app_name = 'dappx'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login',),
]

dprojx/urls.py
from django.contrib import admin
from django.urls import path
from dappx import views
from django.conf.urls import url,include,handler403

# handler403 = 'dappx.views.permission_denied'

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^about$',views.about,name='about'),
    url(r'^contact$',views.contact,name='contact'),
    url(r'^dashboard$',views.dashboard,name='dashboard'),
    url(r'^records$',views.table,name='records'),
    url(r'^accounts$',views.accounts,name='accounts'),
    url(r'^addaccount$',views.addaccount,name='add-account'),
    url(r'^editaccount$',views.editaccount,name='edit-account'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^line_chart$',views.line_chart,name='line_chart'),
    # url(r'^table/$', views.table, name='table'),
]

dappx/models.py
from django.db import models
from django.contrib.auth.models import User
from random import randint
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView

# Create your models here.

# class UserProfileInfoForm(models.Model):    
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     portfolio_site = models.URLField(blank=True)
#     profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
#     def __str__(self):
#         return self.user.username

class NewAccount(models.Model):
    def __str__(self):
        return 'Account added: {}'.format(self.Username)

    Username = models.CharField(max_length=25)
    First_Name = models.CharField(max_length=25)
    Last_Name = models.CharField(max_length=25)
    Category = models.CharField(max_length=25)
    # Category choices begin here
    ADMIN = 'Admin'
    MANAGER = 'Manager'
    EMPLOYEE = 'Employee'
    STAFF = 'Staff'
    CATEGORY_CHOICES = [
        (ADMIN, 'Admin'),
        (MANAGER, 'Manager'),
        (EMPLOYEE, 'Employee'),
        (STAFF, 'Staff'),        
    ]
    Category = models.CharField(
        max_length=10,
        choices=CATEGORY_CHOICES,
        default=ADMIN,
    )
    # Category choices end here

    Status = models.CharField(max_length=25)
    # Status choices begin here
    ACTIVE = 'Active'
    INACTIVE = 'Inactive'        
    STATUS_CHOICES = [
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),               
    ]
    Status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default=ACTIVE,
    )
    # Status choices end here

    Experience = models.CharField(max_length=40)
    # Experience choices begin here
    FRESHER = 'Fresher'
    JUNIOR = 'Junior'
    SENIOR = 'Senior'
    EXPERIENCE_CHOICES = [
        (FRESHER, 'Fresher'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),        
    ]
    Experience = models.CharField(
        max_length=10,
        choices=EXPERIENCE_CHOICES,
        default=FRESHER,
    )
    # Experience choices end here

    Performance = models.CharField(max_length=25)
    # Performance choices begin here
    BAD = 'Bad'
    AVERAGE = 'Average'
    GOOD = 'Good'
    EXCELLENT = 'Excellent'    
    PERFORMANCE_CHOICES = [
        (BAD, 'Bad'),
        (AVERAGE, 'Average'),
        (GOOD, 'Good'),
        (EXCELLENT, 'Excellent'),        
    ]
    Performance = models.CharField(
        max_length=10,
        choices=PERFORMANCE_CHOICES,
        default=AVERAGE,
    )
    # Performance choices end here

    # Define DB table name here
    class meta:
        db_table = "dappx_newaccount"
    
# class AddAccount(models.Model):
#     Username = models.CharField(max_length=25)
#     First_Name = models.CharField(max_length=25)
#     Last_Name = models.CharField(max_length=25)
#     Category = models.CharField(max_length=25)
#     Status = models.CharField(max_length=25)
#     Experience = models.CharField(max_length=25)
#     Performance = models.CharField(max_length=25)
#     class meta:
#         db_table = "dappx_addaccount"

dappx/forms.py
# dappx/forms.py from django import forms
# from dappx.models import UserProfileInfoForm

from django import forms
from .models import NewAccount
from django.contrib.auth.models import User
from django.forms import ModelForm

# Create your models here.

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class RecordsForm(forms.ModelForm):
    class Meta:
        model = NewAccount
        fields = "__all__"

    def clean_Username(self): # Validates the Username Field
        Username = self.cleaned_data.get('Username')
        if (Username == ""):
            raise forms.ValidationError('This field cannot be left blank.')
        for instance in NewAccount.objects.all():
            if instance.Username == Username:
                raise forms.ValidationError('Username already exists. Please try again.')
        return Username

    # class UserProfileInfoForm(forms.ModelForm):
    #     class Meta():
    #         model = UserProfileInfoForm
    #         fields = ('portfolio_site','profile_pic')

dappx/views.py
from django.shortcuts import render, redirect
from dappx.forms import UserForm, RecordsForm
from django.template.context_processors import csrf
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import NewAccount

# Create your views here.

def index(request):
    return render(request,'dappx/index.html')

def about(request):
    return render(request,'dappx/about.html')
    
def contact(request):
    return render(request,'dappx/contact.html')

@login_required
def dashboard(request):
    return render(request,'dappx/dashboard.html')

@login_required
def records(request):   
    return render(request,'dappx/records.html')

def status(request):
    recordsData = dappx_newaccount.objects.all()
    context = {'records': recordsData}
    return render(request,'status.html', context)

@login_required
def accounts(request):
    return render(request,'dappx/accounts.html')

@login_required
def addaccount(request):           
    R_Form= RecordsForm(request.POST or None)
    if request.method == 'POST':
        R_Form=RecordsForm(data=request.POST)
        if R_Form.is_valid():
            user = R_Form.save(commit='True')
            # Hash the password
            R_Form = RecordsForm()
            messages.success(request,'Employee record added successfully.')
        else:
            print("The details you entered are invalid. Please try again.")
    return render(request, 'dappx/add-account.html', {'RecordsForm': R_Form})

@login_required
def editaccount(request):
    return render(request,'dappx/edit-account.html')

def editaccount(request):
    return render(request,'dappx/edit-account.html')
    
@login_required
def special(request):
    return HttpResponse("You have logged in successfully!")
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        user = User.objects.create_user( username=username, email=email, password=password )
        user.save()
        print( "User created successfully." )
        return redirect( 'dappx:user_login' )
    else:
        return render( request, 'dappx/registration.html' )

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return render(request,'dappx/dashboard.html')
            else:
                return HttpResponse("Your account is inactive. Please contact the system administrator.")
        else:
            messages.error(request,'The login details you entered are invalid. Please try again.')
            # messages.error(request, 'Please contact system administrator.', extra_tags='forgot')
            return render(request, 'dappx/login.html')
    else:
        return render(request, 'dappx/login.html', {})

def custom_login(request):
    if request.user.is_authenticated():
        return render(request,'dappx/dashboard.html')
    else:
        return login(request)

def table(request):
    newaccount_Data=NewAccount.objects.all()
    context = {'newaccount_Data' : newaccount_Data}
    return render(request, 'dappx/records.html', context)

def line_chart(request):
    line_chart = TemplateView.as_view(template_name='line_chart.html')
    line_chart_json = LineChartJSONView.as_view()

templates/dappx/login.html
<!DOCTYPE html>
<html lang="en">

<!-- Project Cicada by Taha Mujeeb. 
Copyright © 2020 Taha Mujeeb. All rights reserved.
Any redistribution or reproduction of part or all of the contents in any form is strictly prohibited.
You may not, except with my express written permission, distribute or commercially exploit any content of
these pages. Nor may you transmit it or store it in any other website or other form of electronic retrieval
system. All disputes are subject to Hyderabad, India jurisdiction only. -->

<head>
	<title>Cicada | Login</title>
	{% load static %}
    <meta name="keywords" content="">
	<meta name="description" content="">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel='icon' href='{% static "dappx/favicon.ico" %}' type='image/x-icon'/>

	<!-- stylesheet css -->
	<link rel="stylesheet" href='{% static "dappx/css/bootstrap.fe.css" %}'>
	<link rel="stylesheet" href='{% static "dappx/css/font-awesome.min.css" %}'>
	<!-- <link rel="stylesheet" href="css/nivo-lightbox.css">
	<link rel="stylesheet" href="css/nivo_themes/default/default.css"> -->
	<link rel="stylesheet" href='{% static "dappx/css/style-main.css" %}'>
	<link rel="stylesheet" href='{% static "dappx/css/loginbox.css" %}'>
	<!-- google web font css -->
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

</head>
<body>

<!-- navigation -->

	<div class="container">
		<div class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="{% url 'index' %}" class="navbar-brand"><img src='{% static "dappx/images/logo.png" %}' class="img-responsive" alt="logo"></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'index' %}"><b>HOME</b></a></li>
				<li><a href="{% url 'about' %}"><b>ABOUT</b></a></li>				
				<li><a href="{% url 'contact' %}"><b>CONTACT</b></a></li>
				<li><a href="{% url 'dappx:user_login' %}" class="active"><b>LOGIN</b></a></li>
			</ul>
		</div>
	</div>
</div>		

<!-- portfolio header section -->
<div id="portfolio-header">
	<div class="container">
		<div class="row">
			<div class="row">						
			<div class="col-md-1 col-sm-5"></div>
			<div class="col-sm-4 col-md-10">
			  <!-- <h1 class="text-center text-uppercase"> LOGIN </h1> -->
			</div>		
		</div>
		</div>
	</div>
</div>

<!-- portfolio section -->
<div id="portfolio">
	<div class="container">
		<div class="row">
			<!-- add login code here -->			
			<div class="loginbox">
				<a href="{% url 'dashboard' %}" target="_self">
					<img src='{% static "dappx/images/avatar.png"%}' class="avatar">
				</a>
						<h1>LOGIN</h1>
						{% for message in messages %}
						<div class="alert alert-danger fade in">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							{{ message }}	
						</div>
				{% endfor %}				
						<form method="post" action="{% url 'dappx:user_login' %}">
							{% csrf_token %}
							<p style="text-align:left;">Username</p>
							<input type="text" name="username" placeholder="Enter Username">
							<p style="text-align:left;">Password</p>
							<input type="password" name="password" placeholder="Enter Password">
							<input type="submit" name="" value="Login">
							<a href="#">Forgot password?</a><br>
							<font size="2">Don't have an account?</font> <a href="{% url 'dappx:register' %}">Sign up now!</a>
					</form>
			</div>
		</div>
	</div>
</div>		

<!-- footer section -->
<footer>
	<div class="container">
		<div class="row">
        
			<div class="col-md-5 col-sm-4">
				<img src='{% static "dappx/images/logo.png" %}' class="img-responsive" alt="logo">
				<p>Cicada is designed, developed and maintained by Taha Mujeeb. Feel free to contact me for any queries and suggestions. </p>
				<p><em class="fa fa-phone"></em> <a href="tel:+918790606685">+91 87906 06685</a></p>
				<p><em class="fa fa-envelope-o"></em><a href="mailto:taahamujeeb@gmail.com"target="_blank">taahamujeeb@gmail.com</a></p></p>
				<p><i class="fa fa-globe"></i> <a href="https://www.tahamujeeb.com/">www.tahamujeeb.com</a></p>
			</div>

			<div class="col-md-3 col-sm-4">
				<h3>Useful Links</h3>
				<p><a href="https://www.tahamujeeb.com/"target="_blank">About me</a></p>
				<p><a href="https://drive.google.com/file/d/1DPikYp1IBpsV7o3QWokN_0-VZg62sZ-N/view"target="_blank">My resume</a></p>
			</div>
            
			<div class="col-md-4 col-sm-4 newsletter">
				<h3>Newsletter</h3>
				<p>Subscribe to stay connected! I won't annoy you with any frequent emails, I promise.</p>
				<div class="input-group">
           	    	<form action="#" method="post">
                        <input name="email" type="email" placeholder="Enter your email" class="form-control" autorequired>
                    	<button type="submit" name="submit" class="btn email">Submit</button>
                  	</form>
			  </div>
			</div>
            
		</div>
	</div>
</footer>

<!-- copyright section -->
<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<p>Copyright © 2020 Taha Mujeeb</p>
			</div>
			<div class="col-md-6 col-sm-6">
				<ul class="social-icons">
					<li><a href="https://www.facebook.com/taahamujeeb" target="_blank" class="fa fa-facebook"></a></li>
					<li><a href="https://www.instagram.com/tahamujeeb/" target="_blank" class="fa fa-instagram"></a></li>
					<li><a href="https://wa.me/918790606685" target="_blank" class="fa fa-whatsapp"></a></li>
					<li><a href="https://www.linkedin.com/in/tahamujeeb/" target="_blank" class="fa fa-linkedin"></a></li>
					<li><a href="https://twitter.com/taahamujeeb" target="_blank" class="fa fa-twitter"></a></li>
					<li><a href="https://www.tahamujeeb.com/" target="_blank" class="fa fa-globe"></a></li>					
			  </ul>
			</div>
		</div>
	</div>
</div>

<!-- javascript js -->	
<script src='{% static "dappx/js/jquery.js"%}'></script>
<script src='{% static "dappx/js/bootstrap.fe.js"%}'></script>	
<script src='{% static "dappx/js/nivo-lightbox.min.js"%}'></script>
<!-- <script src='{% static "dappx/js/custom.js"%}'></script> -->

</body>
</html>

templates/dappx/registration.html
<!DOCTYPE html>
<html lang="en">

<!-- Project Cicada by Taha Mujeeb. 
Copyright © 2020 Taha Mujeeb. All rights reserved.
Any redistribution or reproduction of part or all of the contents in any form is strictly prohibited.
You may not, except with my express written permission, distribute or commercially exploit any content of
these pages. Nor may you transmit it or store it in any other website or other form of electronic retrieval
system. All disputes are subject to Hyderabad, India jurisdiction only. -->

<head>
	<title>Cicada | Register</title>
	{% load static %}
    <meta name="keywords" content="">
	<meta name="description" content="">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel='icon' href='{% static "dappx/favicon.ico" %}' type='image/x-icon'/>

	<!-- stylesheet css -->
	<link rel="stylesheet" href='{% static "dappx/css/bootstrap.fe.css" %}'>
	<link rel="stylesheet" href='{% static "dappx/css/font-awesome.min.css" %}'>
	<!-- <link rel="stylesheet" href="css/nivo-lightbox.css">
	<link rel="stylesheet" href="css/nivo_themes/default/default.css"> -->
	<link rel="stylesheet" href='{% static "dappx/css/style-main.css" %}'>
	<style type="text/css">
	body{ margin: 0; padding: 0; background-size: cover; background-position: center; font-family: 'Montserrat', sans-serif; }
    .loginbox{ width: 320px; height: 520px; background: #1C1C1C; color: #fff; top: 65%; left: 50%; position: absolute; transform: translate(-50%,-50%); box-sizing: border-box; padding: 70px 30px; opacity: 0.9;}
    .avatar{ width: 100px !important; height: 100px; transition:none !important; opacity: 1 !important; border-radius: 50%; position: absolute; top: -50px; left: calc(50% - 50px); } h1{ margin: 0; padding: 0 0 20px; text-align: center; font-size: 22px; }
    .loginbox p{ margin: 0; padding: 0; font-weight: bold; }    
    .loginbox input{ width: 100%; margin-bottom: 20px; }
    .loginbox input[type="text"], input[type="password"]{ border: none; border-bottom: 1px solid #fff; background: transparent; outline: none; height: 40px; color: #fff; font-size: 16px; }
	.loginbox input[type="email"], input[type="password"]{ border: none; border-bottom: 1px solid #fff; background: transparent; outline: none; height: 40px; color: #fff; font-size: 16px; }
    .loginbox input[type="submit"]{ border: none; outline: none; height: 40px; background: #337AB7; color: #fff; font-size: 18px; border-radius: 20px; }
    .loginbox input[type="submit"]:hover { cursor: pointer; background: #ffc107; color: #000; }
    .loginbox a{ text-decoration: none; font-size: 12px; line-height: 20px; color: darkgrey; }    
    .loginbox a:hover{ color: #ffc107; }</style>
	<!-- google web font css -->
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

</head>
<body>

<!-- navigation -->

	<div class="container">
		<div class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="{% url 'index' %}" class="navbar-brand"><img src='{% static "dappx/images/logo.png" %}' class="img-responsive" alt="logo"></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'index' %}"><b>HOME</b></a></li>
				<li><a href="{% url 'about' %}"><b>ABOUT</b></a></li>				
				<li><a href="{% url 'contact' %}"><b>CONTACT</b></a></li>
				<li><a href="{% url 'dappx:user_login' %}" class="active"><b>LOGIN</b></a></li>
			</ul>
		</div>
	</div>
</div>		

<!-- portfolio header section -->
<div id="portfolio-header">
	<div class="container">
		<div class="row">
			<div class="row">						
			<div class="col-md-1 col-sm-5"></div>
			<div class="col-sm-4 col-md-10">
			  <!-- <h1 class="text-center text-uppercase"> headergoeshere </h1> -->
			</div>		
		</div>
		</div>
	</div>
</div>

<!-- portfolio section -->
<div id="portfolio">
	<div class="container">
		<div class="row">
			<!-- add login code here -->
			<div class="loginbox">
				<a href="{% url 'dashboard' %}" target="_self">
					<img src='{% static "dappx/images/avatar.png"%}' class="avatar">
				</a>
						<h1>REGISTER</h1>
						<form method="post" action="{% url 'dappx:register' %}">
							{% csrf_token %}
							<p style="text-align:left;">Username</p>
							<input type="text" name="username" placeholder="Enter Username">
							<p style="text-align:left;">Email Address</p>
							<input type="email" name="email" placeholder="Enter email address">
							<p style="text-align:left;">Password</p>
							<input type="password" name="password" placeholder="Enter Password">
							<p style="text-align:left;">Confirm Password</p>
							<input type="password" name="password" placeholder="Re-enter Password">
							<input type="submit" name="" value="Submit">				
					</form>        
			</div>
		</div>
	</div>
</div>		

<!-- footer section -->
<footer>
	<div class="container">
		<div class="row">        
			<div class="col-md-5 col-sm-4">
				<img src='{% static "dappx/images/logo.png" %}' class="img-responsive" alt="logo">
				<p>Cicada is designed, developed and maintained by Taha Mujeeb. Feel free to contact me for any queries and suggestions. </p>
				<p><em class="fa fa-phone"></em> <a href="tel:+918790606685">+91 87906 06685</a></p>
				<p><em class="fa fa-envelope-o"></em><a href="mailto:taahamujeeb@gmail.com"target="_blank">taahamujeeb@gmail.com</a></p></p>
				<p><i class="fa fa-globe"></i> <a href="https://www.tahamujeeb.com/">www.tahamujeeb.com</a></p>
			</div>

			<div class="col-md-3 col-sm-4">
				<h3>Useful Links</h3>
				<p><a href="https://www.tahamujeeb.com/"target="_blank">About me</a></p>
				<p><a href="https://drive.google.com/file/d/1D_MkNQuBjhHwfYM3b8ZuQ87RnQjEVXIm/view"target="_blank"">My resume</a></p>				
			</div>
            
			<div class="col-md-4 col-sm-4 newsletter">
				<h3>Newsletter</h3>
				<p>Subscribe to stay connected! I won't annoy you with any frequent emails, I promise.</p>
				<div class="input-group">
           	    	<form action="#" method="post">
                        <input name="email" type="email" placeholder="Enter your email" class="form-control" autorequired>
                    	<button type="submit" name="submit" class="btn email">Submit</button>
                  	</form>
			  </div>
			</div>
            
		</div>
	</div>
</footer>

<!-- copyright section -->
<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<p>Copyright © 2020 Taha Mujeeb</p>
			</div>
			<div class="col-md-6 col-sm-6">
				<ul class="social-icons">
					<li><a href="https://www.facebook.com/taahamujeeb" class="fa fa-facebook"></a></li>
					<li><a href="https://www.instagram.com/tahamujeeb/" class="fa fa-instagram"></a></li>
					<li><a href="https://wa.me/918790606685" class="fa fa-whatsapp"></a></li>
					<li><a href="https://www.linkedin.com/in/tahamujeeb/" class="fa fa-linkedin"></a></li>
					<li><a href="https://twitter.com/taahamujeeb" class="fa fa-twitter"></a></li>
					<li><a href="https://www.tahamujeeb.com/" class="fa fa-globe"></a></li>					
			  </ul>
			</div>
		</div>
	</div>
</div>

<!-- javascript js -->	
<script src="js/jquery.js"></script>
<script src="js/bootstrap.fe.js"></script>	
<script src="js/nivo-lightbox.min.js"></script>
<script src="js/custom.js"></script>

</body>
</html>